version: '3.8'

services:
  mysqldb:
    image: arm64v8/mysql:oracle
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    image: custom_reservations/node:latest
    depends_on:
      - mysqldb
    # build: ./custom-reservations
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - 9229:9229
    volumes:
      - .:/app
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - FIC_CLIENT_ID=$FIC_CLIENT_ID
      - FIC_CLIENT_SECRET=$FIC_CLIENT_SECRET
      - URL=$URL
    stdin_open: true
    tty: true

volumes: 
  db:
